services:
  - type: web
    name: vocabulary-api
    env: python
    region: frankfurt
    buildCommand: |
      # Принудительно устанавливаем Python 3.11
      pyenv install 3.11.9 -s
      pyenv global 3.11.9
      # Устанавливаем зависимости
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: vocabulary-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: vocabulary-db
    plan: free