services:
  - type: web
    name: vocabulary-api
    env: python
    region: frankfurt  # или другой регион
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vocabulary-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: vocabulary-db
    plan: free
    databaseName: vocabulary
    user: vocabulary_user